### ISSUE TITLE
forgebox install is broken

### ISSUE THREAD

**Issue by SkyDocker** [coldfumonkeh/PicPurify#1]
Really looking forward to using this but forgebox installtion is broken. 

![image](https://user-images.githubusercontent.com/42099700/82575414-4c155c00-9b3d-11ea-82b0-93c22b9e16ac.png)

**Comment by coldfumonkeh** [comment]
Hi

Apologies for the late reply. This should be fixed now as there is a tag in the repository.

Many thanks

**Comment by SkyDocker** [comment]
Sorry, still no luck.

![image](https://user-images.githubusercontent.com/42099700/82676692-a70d8880-9bfb-11ea-8167-85bebb1b65cc.png)

**Comment by coldfumonkeh** [comment]
@SkyDocker Definitely fixed now, apologies. I bumped to version 1.0.1 to make sure the tag was present and updated. Tested locally with a successful install from Forgebox

**Comment by SkyDocker** [comment]
Thank you.  It installs now, but it's failing on injection:

![image](https://user-images.githubusercontent.com/42099700/82697622-1b592380-9c1e-11ea-8fa8-57405957053f.png)

Below is how I'm trying to instantiate it (the persistent = false is a quick orm flag that tells it that this is not a database field):

![image](https://user-images.githubusercontent.com/42099700/82698071-fc0ec600-9c1e-11ea-9c19-db0c7bc933a8.png)


The readme says that I also need to initialize the component using the following code, but usually wirebox handles the initialization and it should be pulling the api key from coldbox.cfc.  I'm not sure what to do with this...

```
        picpurify = new picpurify( APIKey = 'mykey' );
```

**Comment by coldfumonkeh** [comment]
@SkyDocker Have you seen the README file for this repository? It has the code you need to add the module to the Coldbox configuration file:

```
picpurify = {
     apiKey = '<YOUR_API_KEY_GOES_HERE>' // Your PicPurify API Key
};
```

**Comment by SkyDocker** [comment]
We do have that code in our Coldbox.cfc file but we are still getting this error.

![image](https://user-images.githubusercontent.com/42099700/82741463-f2f92400-9d06-11ea-9a9c-162a4d5b5e93.png)
